### ISSUE TITLE
Question about Ground Connection

### ISSUE THREAD

**Issue by ref5275** [johnboiles/BaofengUV5R-TRRS#11]
I noticed on your schematic the ground is connected to the tip on the trrs plug which is one of the audio out channels. Is this the correct place to connect the ground or should it be the 2nd ring from the bottom?

**Comment by saivert** [comment]
You are reading the schematic incorrectly. The rectangular thick spot on the far right is the sleeve which is the mic. The first contact point to the left of this is the first ring which is the grounding. Then comes another ring which is the first audio channel and finally the tip which is the second audio channel.

**Comment by johnboiles** [comment]
Thanks @saivert for responding, and my apologies @ref5275 for not responding sooner. That schematic symbol certainly is a little confusing. Might be better to make one that looks like a male trrs plug instead with arrows to the trip, rings & sleeve
