### ISSUE TITLE
Connecting headset and phone

### ISSUE THREAD

**Issue by fossum** [johnboiles/BaofengUV5R-TRRS#9]
Forgive me, I'm new to this whole ham thing and I'd like to run motorcycle groups comms through the one band on the ham and arps on the other. Is this possible with a [BaoFeng UV-82HP](http://www.amazon.com/BaoFeng-UV-82HP-YELLOW-Power-Radio/dp/B015D9QYYS?ie=UTF8&psc=1&redirect=true&ref_=oh_aui_detailpage_o01_s00) and your PCB?

Sorry for filing an issue, but I didn't see any other way...

**Comment by johnboiles** [comment]
Hi @fossum. You probably can't use the same radio for both duties at the same time, but that radio should be fine for either duty.

Two things to note about this project
1) The interesting part of this project is in the RX (tricks the phone into thinking an external microphone is attached). TX can be accomplished with a simple patch cable. Some users have reported that vox gets continuously triggered with this cable when using it for TX. Personally I use standalone devices for TX (see [tinytrackuino](https://github.com/johnboiles/tinytrackuino)) and only use this cable for RX.
2) It's designed to be the cheapest way to use APRS in a pinch. Think of it like a tool you have in your toolbox for APRS, but not a bulletproof way to send and receive packets. A proper TNC might make more sense if this is something you're relying on day-to-day.

**Comment by fossum** [comment]
Right, I figured you can't TX on two bands at the same time. I thought I'd just silence the APRSdroid when talking (through some custom PCB). This Trackuino seems interesting. Probably more along what I need. Thanks for the redirect.
